### ISSUE TITLE
Alarm does not create

### ISSUE THREAD

**Issue by goodyMassMedical** [marklogic/cloud-enablement#82]
We see this error:

  | 14:38:24 UTC-0400 | CREATE_FAILED | AWS::CloudWatch::Alarm | InstanceRecoveryAlarm1 | Invalid use of EC2 action. An EC2 action can only be used if the alarm is monitoring an EC2 instance. (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError; Request ID: 82de620d-c73b-11e8-8993-2937106b7512)

I saw this with your stack earlier last week and opened a support request with AWS. They told me this:

Hello,

Thank you for contacting AWS Support, I'm Mansi and I will be assisting you with the case today.

I understand that you are seeing the following error when attempting to create a CloudWatch Alarm in your stack:

"Invalid use of EC2 action. An EC2 action can only be used if the alarm is monitoring an EC2 instance. (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError; Request ID: 5a013998-c0ea-11e8-9cf1-154b587d0f70)"

After further investigating the issue and taking a look at your CloudFormation template, I see that the following alarm failed to create:

  InstanceRecoveryAlarm1:
    Type: AWS::CloudWatch::Alarm
    DependsOn: MarkLogicServerGroup1
    Properties:
      AlarmDescription: Trigger a recovery when instance status check fails for 1 consecutive minutes.
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Statistic: Minimum
      Period: '60'
      EvaluationPeriods: '1'
      ComparisonOperator: GreaterThanThreshold
      Threshold: '0'
      AlarmActions:
        - !Join ['',["arn:aws:automate:", !Ref "AWS::Region", ":ec2:recover"]]
        - !If [UseLogSNS, !Ref LogSNS ,!Ref 'AWS::NoValue']
      OKActions:
        - !If [UseLogSNS, !Ref LogSNS ,!Ref 'AWS::NoValue']
      Dimensions:
        - Name: ASG1
          Value: !Ref MarkLogicServerGroup1

The reason you are getting this error is because the CloudWatch alarm is setup to monitor an Auto Scaling group, however the recover action it is being configured to perform is only for EC2 instances [1]. Referring to the alarm configuration above, I see that the "StatusCheckFailed_System" metric, which is only applicable in the AWS/EC2 namespace, has an Auto Scaling group, "MarkLogicServerGroup1", dimension attached to it.

[1] Adding Recover Actions to Amazon CloudWatch Alarms - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UsingAlarmActions.html#AddingRecoverActions

Unfortunately, EC2 recover actions cannot be performed on Auto Scaling group resources, they can only be performed on individual EC2 instances. The alarm would have to be monitoring individual EC2 instance IDs in order to be able to perform this action. So in order to resolve the error, you have to list the specific EC2 instance IDs you would like to be monitored in the Dimensions property instead of the Auto Scaling group.

One thing to note is that instances in Auto Scaling groups are scheduled for immediate replacement if they fail EC2 system health checks. Once the problematic instance is brought down, a new instance will be added to the Auto Scaling group automatically to replace it. So depending on your use case, you may not need the CloudWatch alarm at all if you are just looking for the instances to be replaced automatically should they fail the EC2 system health check. More information on how Auto Scaling replaces unhealthy instances can be found here [2].

[2] Auto Scaling Group  - Replacing Unhealthy Instances - https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-maintain-instance-levels.html#replace-unhealthy-instance

You mentioned that in the past, creating an alarm in this manner hasn't proved to be a problem. To see why this might be, I reached out to our internal service team and they were able to confirm that recently, additional validations were added for recover actions requests for the PutMetricAlarm API call. Due to these additional validations at the API level, the stack failed to create the CloudWatch alarm metric.

I hope the above information helps. If you have any further questions or inquiries, please feel free to contact us.

Best regards,

Mansi V.
Amazon Web Services

**Comment by lhy-loveworld** [comment]
Hi @goodyMassMedical , thanks for your reaching out. We also saw this problem recently during our nightly build. And we also contacted AWS and got the same response from them as you did. The reason is that they recently changed their internal API. And the solution is simply removing InstanceRecoveryAlarm1, InstanceRecoveryAlarm2 and InstanceRecoveryAlarm3 from mlcluster-vpc.template and mlcluster.template. If you have any other problems, please let us know!

**Comment by mattsunsjf** [comment]
In the coming release, we will remove the alarm.
